//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Client.Wars {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wars.WarsWebServiceSoap")]
    public interface WarsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ReturnListOfWarsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnListOfWars", ReplyAction="*")]
        Lab1Client.Wars.ReturnListOfWarsResponse ReturnListOfWars(Lab1Client.Wars.ReturnListOfWarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnListOfWars", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1Client.Wars.ReturnListOfWarsResponse> ReturnListOfWarsAsync(Lab1Client.Wars.ReturnListOfWarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnListOfWarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnListOfWars", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.Wars.ReturnListOfWarsRequestBody Body;
        
        public ReturnListOfWarsRequest() {
        }
        
        public ReturnListOfWarsRequest(Lab1Client.Wars.ReturnListOfWarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReturnListOfWarsRequestBody {
        
        public ReturnListOfWarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnListOfWarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnListOfWarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.Wars.ReturnListOfWarsResponseBody Body;
        
        public ReturnListOfWarsResponse() {
        }
        
        public ReturnListOfWarsResponse(Lab1Client.Wars.ReturnListOfWarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnListOfWarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab1Client.Wars.ArrayOfString ReturnListOfWarsResult;
        
        public ReturnListOfWarsResponseBody() {
        }
        
        public ReturnListOfWarsResponseBody(Lab1Client.Wars.ArrayOfString ReturnListOfWarsResult) {
            this.ReturnListOfWarsResult = ReturnListOfWarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WarsWebServiceSoapChannel : Lab1Client.Wars.WarsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarsWebServiceSoapClient : System.ServiceModel.ClientBase<Lab1Client.Wars.WarsWebServiceSoap>, Lab1Client.Wars.WarsWebServiceSoap {
        
        public WarsWebServiceSoapClient() {
        }
        
        public WarsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1Client.Wars.ReturnListOfWarsResponse Lab1Client.Wars.WarsWebServiceSoap.ReturnListOfWars(Lab1Client.Wars.ReturnListOfWarsRequest request) {
            return base.Channel.ReturnListOfWars(request);
        }
        
        public Lab1Client.Wars.ArrayOfString ReturnListOfWars() {
            Lab1Client.Wars.ReturnListOfWarsRequest inValue = new Lab1Client.Wars.ReturnListOfWarsRequest();
            inValue.Body = new Lab1Client.Wars.ReturnListOfWarsRequestBody();
            Lab1Client.Wars.ReturnListOfWarsResponse retVal = ((Lab1Client.Wars.WarsWebServiceSoap)(this)).ReturnListOfWars(inValue);
            return retVal.Body.ReturnListOfWarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1Client.Wars.ReturnListOfWarsResponse> Lab1Client.Wars.WarsWebServiceSoap.ReturnListOfWarsAsync(Lab1Client.Wars.ReturnListOfWarsRequest request) {
            return base.Channel.ReturnListOfWarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1Client.Wars.ReturnListOfWarsResponse> ReturnListOfWarsAsync() {
            Lab1Client.Wars.ReturnListOfWarsRequest inValue = new Lab1Client.Wars.ReturnListOfWarsRequest();
            inValue.Body = new Lab1Client.Wars.ReturnListOfWarsRequestBody();
            return ((Lab1Client.Wars.WarsWebServiceSoap)(this)).ReturnListOfWarsAsync(inValue);
        }
    }
}
