//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Client.AddTwoNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddTwoNumbers.AddsTwoNumbersSoap")]
    public interface AddsTwoNumbersSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        int AddNumbers(int numberOne, int numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddNumbersAsync(int numberOne, int numberTwo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddsTwoNumbersSoapChannel : Lab1Client.AddTwoNumbers.AddsTwoNumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddsTwoNumbersSoapClient : System.ServiceModel.ClientBase<Lab1Client.AddTwoNumbers.AddsTwoNumbersSoap>, Lab1Client.AddTwoNumbers.AddsTwoNumbersSoap {
        
        public AddsTwoNumbersSoapClient() {
        }
        
        public AddsTwoNumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddsTwoNumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddsTwoNumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddsTwoNumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddNumbers(int numberOne, int numberTwo) {
            return base.Channel.AddNumbers(numberOne, numberTwo);
        }
        
        public System.Threading.Tasks.Task<int> AddNumbersAsync(int numberOne, int numberTwo) {
            return base.Channel.AddNumbersAsync(numberOne, numberTwo);
        }
    }
}
