//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Lab2._1000Days", ConfigurationName="INext1000Days")]
public interface INext1000Days
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Lab2._1000Days/INext1000Days/CalculateNext1000Days", ReplyAction="http://Lab2._1000Days/INext1000Days/CalculateNext1000DaysResponse")]
    string CalculateNext1000Days(System.DateTime birthday);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Lab2._1000Days/INext1000Days/CalculateNext1000Days", ReplyAction="http://Lab2._1000Days/INext1000Days/CalculateNext1000DaysResponse")]
    System.Threading.Tasks.Task<string> CalculateNext1000DaysAsync(System.DateTime birthday);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INext1000DaysChannel : INext1000Days, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Next1000DaysClient : System.ServiceModel.ClientBase<INext1000Days>, INext1000Days
{
    
    public Next1000DaysClient()
    {
    }
    
    public Next1000DaysClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Next1000DaysClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Next1000DaysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Next1000DaysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string CalculateNext1000Days(System.DateTime birthday)
    {
        return base.Channel.CalculateNext1000Days(birthday);
    }
    
    public System.Threading.Tasks.Task<string> CalculateNext1000DaysAsync(System.DateTime birthday)
    {
        return base.Channel.CalculateNext1000DaysAsync(birthday);
    }
}
