//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://schemas.datacontract.org/2004/07/NorthwindService")]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private System.DateTime BirthDateField;
        
        private string CityField;
        
        private string FirstNameField;
        
        private System.DateTime HireDateField;
        
        private int IDField;
        
        private string LastNameField;
        
        private string TitleField;
        
        private string TitleOfCourtesyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HireDate
        {
            get
            {
                return this.HireDateField;
            }
            set
            {
                this.HireDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleOfCourtesy
        {
            get
            {
                return this.TitleOfCourtesyField;
            }
            set
            {
                this.TitleOfCourtesyField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEmployeesService")]
public interface IEmployeesService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesService/GetEmployee", ReplyAction="http://tempuri.org/IEmployeesService/GetEmployeeResponse")]
    NorthwindService.Employees GetEmployee(int ID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesService/GetEmployee", ReplyAction="http://tempuri.org/IEmployeesService/GetEmployeeResponse")]
    System.Threading.Tasks.Task<NorthwindService.Employees> GetEmployeeAsync(int ID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesService/EditEmployee", ReplyAction="http://tempuri.org/IEmployeesService/EditEmployeeResponse")]
    void EditEmployee(NorthwindService.Employees employee);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeesService/EditEmployee", ReplyAction="http://tempuri.org/IEmployeesService/EditEmployeeResponse")]
    System.Threading.Tasks.Task EditEmployeeAsync(NorthwindService.Employees employee);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEmployeesServiceChannel : IEmployeesService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EmployeesServiceClient : System.ServiceModel.ClientBase<IEmployeesService>, IEmployeesService
{
    
    public EmployeesServiceClient()
    {
    }
    
    public EmployeesServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EmployeesServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmployeesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmployeesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public NorthwindService.Employees GetEmployee(int ID)
    {
        return base.Channel.GetEmployee(ID);
    }
    
    public System.Threading.Tasks.Task<NorthwindService.Employees> GetEmployeeAsync(int ID)
    {
        return base.Channel.GetEmployeeAsync(ID);
    }
    
    public void EditEmployee(NorthwindService.Employees employee)
    {
        base.Channel.EditEmployee(employee);
    }
    
    public System.Threading.Tasks.Task EditEmployeeAsync(NorthwindService.Employees employee)
    {
        return base.Channel.EditEmployeeAsync(employee);
    }
}
