//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Client.AddThreeNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddThreeNumbers.AddThreeNumbersSoap")]
    public interface AddThreeNumbersSoap {
        
        // CODEGEN: Generating message contract since element name AddNumbersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        Lab1Client.AddThreeNumbers.AddNumbersResponse AddNumbers(Lab1Client.AddThreeNumbers.AddNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1Client.AddThreeNumbers.AddNumbersResponse> AddNumbersAsync(Lab1Client.AddThreeNumbers.AddNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.AddThreeNumbers.AddNumbersRequestBody Body;
        
        public AddNumbersRequest() {
        }
        
        public AddNumbersRequest(Lab1Client.AddThreeNumbers.AddNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numberOne;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int numberTwo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numberThree;
        
        public AddNumbersRequestBody() {
        }
        
        public AddNumbersRequestBody(int numberOne, int numberTwo, int numberThree) {
            this.numberOne = numberOne;
            this.numberTwo = numberTwo;
            this.numberThree = numberThree;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.AddThreeNumbers.AddNumbersResponseBody Body;
        
        public AddNumbersResponse() {
        }
        
        public AddNumbersResponse(Lab1Client.AddThreeNumbers.AddNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNumbersResult;
        
        public AddNumbersResponseBody() {
        }
        
        public AddNumbersResponseBody(string AddNumbersResult) {
            this.AddNumbersResult = AddNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddThreeNumbersSoapChannel : Lab1Client.AddThreeNumbers.AddThreeNumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddThreeNumbersSoapClient : System.ServiceModel.ClientBase<Lab1Client.AddThreeNumbers.AddThreeNumbersSoap>, Lab1Client.AddThreeNumbers.AddThreeNumbersSoap {
        
        public AddThreeNumbersSoapClient() {
        }
        
        public AddThreeNumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddThreeNumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddThreeNumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddThreeNumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1Client.AddThreeNumbers.AddNumbersResponse Lab1Client.AddThreeNumbers.AddThreeNumbersSoap.AddNumbers(Lab1Client.AddThreeNumbers.AddNumbersRequest request) {
            return base.Channel.AddNumbers(request);
        }
        
        public string AddNumbers(int numberOne, int numberTwo, int numberThree) {
            Lab1Client.AddThreeNumbers.AddNumbersRequest inValue = new Lab1Client.AddThreeNumbers.AddNumbersRequest();
            inValue.Body = new Lab1Client.AddThreeNumbers.AddNumbersRequestBody();
            inValue.Body.numberOne = numberOne;
            inValue.Body.numberTwo = numberTwo;
            inValue.Body.numberThree = numberThree;
            Lab1Client.AddThreeNumbers.AddNumbersResponse retVal = ((Lab1Client.AddThreeNumbers.AddThreeNumbersSoap)(this)).AddNumbers(inValue);
            return retVal.Body.AddNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1Client.AddThreeNumbers.AddNumbersResponse> Lab1Client.AddThreeNumbers.AddThreeNumbersSoap.AddNumbersAsync(Lab1Client.AddThreeNumbers.AddNumbersRequest request) {
            return base.Channel.AddNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1Client.AddThreeNumbers.AddNumbersResponse> AddNumbersAsync(int numberOne, int numberTwo, int numberThree) {
            Lab1Client.AddThreeNumbers.AddNumbersRequest inValue = new Lab1Client.AddThreeNumbers.AddNumbersRequest();
            inValue.Body = new Lab1Client.AddThreeNumbers.AddNumbersRequestBody();
            inValue.Body.numberOne = numberOne;
            inValue.Body.numberTwo = numberTwo;
            inValue.Body.numberThree = numberThree;
            return ((Lab1Client.AddThreeNumbers.AddThreeNumbersSoap)(this)).AddNumbersAsync(inValue);
        }
    }
}
