//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipper", Namespace="http://schemas.datacontract.org/2004/07/NorthwindService")]
    public partial class Shipper : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CompanyNameField;
        
        private string IDField;
        
        private string PhoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ShipperService", ConfigurationName="IShipperService")]
public interface IShipperService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShipperService/IShipperService/GetShipper", ReplyAction="http://ShipperService/IShipperService/GetShipperResponse")]
    NorthwindService.Shipper GetShipper(string ID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShipperService/IShipperService/GetShipper", ReplyAction="http://ShipperService/IShipperService/GetShipperResponse")]
    System.Threading.Tasks.Task<NorthwindService.Shipper> GetShipperAsync(string ID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShipperService/IShipperService/SaveShipper", ReplyAction="http://ShipperService/IShipperService/SaveShipperResponse")]
    void SaveShipper(NorthwindService.Shipper shipper);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ShipperService/IShipperService/SaveShipper", ReplyAction="http://ShipperService/IShipperService/SaveShipperResponse")]
    System.Threading.Tasks.Task SaveShipperAsync(NorthwindService.Shipper shipper);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IShipperServiceChannel : IShipperService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ShipperServiceClient : System.ServiceModel.ClientBase<IShipperService>, IShipperService
{
    
    public ShipperServiceClient()
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public NorthwindService.Shipper GetShipper(string ID)
    {
        return base.Channel.GetShipper(ID);
    }
    
    public System.Threading.Tasks.Task<NorthwindService.Shipper> GetShipperAsync(string ID)
    {
        return base.Channel.GetShipperAsync(ID);
    }
    
    public void SaveShipper(NorthwindService.Shipper shipper)
    {
        base.Channel.SaveShipper(shipper);
    }
    
    public System.Threading.Tasks.Task SaveShipperAsync(NorthwindService.Shipper shipper)
    {
        return base.Channel.SaveShipperAsync(shipper);
    }
}
