//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Lab2.Service.BMI", ConfigurationName="IBMI")]
public interface IBMI
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Lab2.Service.BMI/IBMI/CalculateBMI", ReplyAction="http://Lab2.Service.BMI/IBMI/CalculateBMIResponse")]
    string CalculateBMI(int weight, double length);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Lab2.Service.BMI/IBMI/CalculateBMI", ReplyAction="http://Lab2.Service.BMI/IBMI/CalculateBMIResponse")]
    System.Threading.Tasks.Task<string> CalculateBMIAsync(int weight, double length);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBMIChannel : IBMI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BMIClient : System.ServiceModel.ClientBase<IBMI>, IBMI
{
    
    public BMIClient()
    {
    }
    
    public BMIClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BMIClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string CalculateBMI(int weight, double length)
    {
        return base.Channel.CalculateBMI(weight, length);
    }
    
    public System.Threading.Tasks.Task<string> CalculateBMIAsync(int weight, double length)
    {
        return base.Channel.CalculateBMIAsync(weight, length);
    }
}
