//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Client.ComputerGames {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComputerGames.ComputerGamesWebServiceSoap")]
    public interface ComputerGamesWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ReturnListOfGameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnListOfGame", ReplyAction="*")]
        Lab1Client.ComputerGames.ReturnListOfGameResponse ReturnListOfGame(Lab1Client.ComputerGames.ReturnListOfGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnListOfGame", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1Client.ComputerGames.ReturnListOfGameResponse> ReturnListOfGameAsync(Lab1Client.ComputerGames.ReturnListOfGameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnListOfGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnListOfGame", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.ComputerGames.ReturnListOfGameRequestBody Body;
        
        public ReturnListOfGameRequest() {
        }
        
        public ReturnListOfGameRequest(Lab1Client.ComputerGames.ReturnListOfGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReturnListOfGameRequestBody {
        
        public ReturnListOfGameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnListOfGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnListOfGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.ComputerGames.ReturnListOfGameResponseBody Body;
        
        public ReturnListOfGameResponse() {
        }
        
        public ReturnListOfGameResponse(Lab1Client.ComputerGames.ReturnListOfGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnListOfGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab1Client.ComputerGames.ArrayOfString ReturnListOfGameResult;
        
        public ReturnListOfGameResponseBody() {
        }
        
        public ReturnListOfGameResponseBody(Lab1Client.ComputerGames.ArrayOfString ReturnListOfGameResult) {
            this.ReturnListOfGameResult = ReturnListOfGameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComputerGamesWebServiceSoapChannel : Lab1Client.ComputerGames.ComputerGamesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComputerGamesWebServiceSoapClient : System.ServiceModel.ClientBase<Lab1Client.ComputerGames.ComputerGamesWebServiceSoap>, Lab1Client.ComputerGames.ComputerGamesWebServiceSoap {
        
        public ComputerGamesWebServiceSoapClient() {
        }
        
        public ComputerGamesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComputerGamesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputerGamesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputerGamesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1Client.ComputerGames.ReturnListOfGameResponse Lab1Client.ComputerGames.ComputerGamesWebServiceSoap.ReturnListOfGame(Lab1Client.ComputerGames.ReturnListOfGameRequest request) {
            return base.Channel.ReturnListOfGame(request);
        }
        
        public Lab1Client.ComputerGames.ArrayOfString ReturnListOfGame() {
            Lab1Client.ComputerGames.ReturnListOfGameRequest inValue = new Lab1Client.ComputerGames.ReturnListOfGameRequest();
            inValue.Body = new Lab1Client.ComputerGames.ReturnListOfGameRequestBody();
            Lab1Client.ComputerGames.ReturnListOfGameResponse retVal = ((Lab1Client.ComputerGames.ComputerGamesWebServiceSoap)(this)).ReturnListOfGame(inValue);
            return retVal.Body.ReturnListOfGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1Client.ComputerGames.ReturnListOfGameResponse> Lab1Client.ComputerGames.ComputerGamesWebServiceSoap.ReturnListOfGameAsync(Lab1Client.ComputerGames.ReturnListOfGameRequest request) {
            return base.Channel.ReturnListOfGameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1Client.ComputerGames.ReturnListOfGameResponse> ReturnListOfGameAsync() {
            Lab1Client.ComputerGames.ReturnListOfGameRequest inValue = new Lab1Client.ComputerGames.ReturnListOfGameRequest();
            inValue.Body = new Lab1Client.ComputerGames.ReturnListOfGameRequestBody();
            return ((Lab1Client.ComputerGames.ComputerGamesWebServiceSoap)(this)).ReturnListOfGameAsync(inValue);
        }
    }
}
