//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Client.SubtractTwoNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubtractTwoNumbers.SubtractTwoNumbersSoap")]
    public interface SubtractTwoNumbersSoap {
        
        // CODEGEN: Generating message contract since element name SubtractResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        Lab1Client.SubtractTwoNumbers.SubtractResponse Subtract(Lab1Client.SubtractTwoNumbers.SubtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1Client.SubtractTwoNumbers.SubtractResponse> SubtractAsync(Lab1Client.SubtractTwoNumbers.SubtractRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Subtract", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.SubtractTwoNumbers.SubtractRequestBody Body;
        
        public SubtractRequest() {
        }
        
        public SubtractRequest(Lab1Client.SubtractTwoNumbers.SubtractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numberOne;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int numberTwo;
        
        public SubtractRequestBody() {
        }
        
        public SubtractRequestBody(int numberOne, int numberTwo) {
            this.numberOne = numberOne;
            this.numberTwo = numberTwo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.SubtractTwoNumbers.SubtractResponseBody Body;
        
        public SubtractResponse() {
        }
        
        public SubtractResponse(Lab1Client.SubtractTwoNumbers.SubtractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubtractResult;
        
        public SubtractResponseBody() {
        }
        
        public SubtractResponseBody(string SubtractResult) {
            this.SubtractResult = SubtractResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubtractTwoNumbersSoapChannel : Lab1Client.SubtractTwoNumbers.SubtractTwoNumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubtractTwoNumbersSoapClient : System.ServiceModel.ClientBase<Lab1Client.SubtractTwoNumbers.SubtractTwoNumbersSoap>, Lab1Client.SubtractTwoNumbers.SubtractTwoNumbersSoap {
        
        public SubtractTwoNumbersSoapClient() {
        }
        
        public SubtractTwoNumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubtractTwoNumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubtractTwoNumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubtractTwoNumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1Client.SubtractTwoNumbers.SubtractResponse Lab1Client.SubtractTwoNumbers.SubtractTwoNumbersSoap.Subtract(Lab1Client.SubtractTwoNumbers.SubtractRequest request) {
            return base.Channel.Subtract(request);
        }
        
        public string Subtract(int numberOne, int numberTwo) {
            Lab1Client.SubtractTwoNumbers.SubtractRequest inValue = new Lab1Client.SubtractTwoNumbers.SubtractRequest();
            inValue.Body = new Lab1Client.SubtractTwoNumbers.SubtractRequestBody();
            inValue.Body.numberOne = numberOne;
            inValue.Body.numberTwo = numberTwo;
            Lab1Client.SubtractTwoNumbers.SubtractResponse retVal = ((Lab1Client.SubtractTwoNumbers.SubtractTwoNumbersSoap)(this)).Subtract(inValue);
            return retVal.Body.SubtractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1Client.SubtractTwoNumbers.SubtractResponse> Lab1Client.SubtractTwoNumbers.SubtractTwoNumbersSoap.SubtractAsync(Lab1Client.SubtractTwoNumbers.SubtractRequest request) {
            return base.Channel.SubtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1Client.SubtractTwoNumbers.SubtractResponse> SubtractAsync(int numberOne, int numberTwo) {
            Lab1Client.SubtractTwoNumbers.SubtractRequest inValue = new Lab1Client.SubtractTwoNumbers.SubtractRequest();
            inValue.Body = new Lab1Client.SubtractTwoNumbers.SubtractRequestBody();
            inValue.Body.numberOne = numberOne;
            inValue.Body.numberTwo = numberTwo;
            return ((Lab1Client.SubtractTwoNumbers.SubtractTwoNumbersSoap)(this)).SubtractAsync(inValue);
        }
    }
}
