//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Lab.Hobby", ConfigurationName="IHobby")]
public interface IHobby
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Lab.Hobby/IHobby/Shoes", ReplyAction="http://Lab.Hobby/IHobby/ShoesResponse")]
    string Shoes(string gender, [System.ServiceModel.MessageParameterAttribute(Name="shoes")] string shoes1, int size);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Lab.Hobby/IHobby/Shoes", ReplyAction="http://Lab.Hobby/IHobby/ShoesResponse")]
    System.Threading.Tasks.Task<string> ShoesAsync(string gender, string shoes, int size);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHobbyChannel : IHobby, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HobbyClient : System.ServiceModel.ClientBase<IHobby>, IHobby
{
    
    public HobbyClient()
    {
    }
    
    public HobbyClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HobbyClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HobbyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HobbyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Shoes(string gender, string shoes1, int size)
    {
        return base.Channel.Shoes(gender, shoes1, size);
    }
    
    public System.Threading.Tasks.Task<string> ShoesAsync(string gender, string shoes, int size)
    {
        return base.Channel.ShoesAsync(gender, shoes, size);
    }
}
