//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Client.NameDay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NameDay.NameDay1Soap")]
    public interface NameDay1Soap {
        
        // CODEGEN: Generating message contract since element name inputName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnDay", ReplyAction="*")]
        Lab1Client.NameDay.ReturnDayResponse ReturnDay(Lab1Client.NameDay.ReturnDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnDay", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab1Client.NameDay.ReturnDayResponse> ReturnDayAsync(Lab1Client.NameDay.ReturnDayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnDay", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.NameDay.ReturnDayRequestBody Body;
        
        public ReturnDayRequest() {
        }
        
        public ReturnDayRequest(Lab1Client.NameDay.ReturnDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputName;
        
        public ReturnDayRequestBody() {
        }
        
        public ReturnDayRequestBody(string inputName) {
            this.inputName = inputName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab1Client.NameDay.ReturnDayResponseBody Body;
        
        public ReturnDayResponse() {
        }
        
        public ReturnDayResponse(Lab1Client.NameDay.ReturnDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReturnDayResult;
        
        public ReturnDayResponseBody() {
        }
        
        public ReturnDayResponseBody(string ReturnDayResult) {
            this.ReturnDayResult = ReturnDayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NameDay1SoapChannel : Lab1Client.NameDay.NameDay1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NameDay1SoapClient : System.ServiceModel.ClientBase<Lab1Client.NameDay.NameDay1Soap>, Lab1Client.NameDay.NameDay1Soap {
        
        public NameDay1SoapClient() {
        }
        
        public NameDay1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NameDay1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameDay1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameDay1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab1Client.NameDay.ReturnDayResponse Lab1Client.NameDay.NameDay1Soap.ReturnDay(Lab1Client.NameDay.ReturnDayRequest request) {
            return base.Channel.ReturnDay(request);
        }
        
        public string ReturnDay(string inputName) {
            Lab1Client.NameDay.ReturnDayRequest inValue = new Lab1Client.NameDay.ReturnDayRequest();
            inValue.Body = new Lab1Client.NameDay.ReturnDayRequestBody();
            inValue.Body.inputName = inputName;
            Lab1Client.NameDay.ReturnDayResponse retVal = ((Lab1Client.NameDay.NameDay1Soap)(this)).ReturnDay(inValue);
            return retVal.Body.ReturnDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab1Client.NameDay.ReturnDayResponse> Lab1Client.NameDay.NameDay1Soap.ReturnDayAsync(Lab1Client.NameDay.ReturnDayRequest request) {
            return base.Channel.ReturnDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab1Client.NameDay.ReturnDayResponse> ReturnDayAsync(string inputName) {
            Lab1Client.NameDay.ReturnDayRequest inValue = new Lab1Client.NameDay.ReturnDayRequest();
            inValue.Body = new Lab1Client.NameDay.ReturnDayRequestBody();
            inValue.Body.inputName = inputName;
            return ((Lab1Client.NameDay.NameDay1Soap)(this)).ReturnDayAsync(inValue);
        }
    }
}
